---
title: El Modelo de Regresión Lineal Simple
author:
- name: VE-CC-AJ
  affiliation: DataIntelligence
subtitle: | 

date: "Miércoles 30-06-2021"

abstract: |
  Desarrollamos los fundamentos teóricos del análisis de regresión lineal
    
header-includes:
   - \usepackage[]{babel}

output:
  html_document:
    toc: true
    toc_float: true
    theme: flatly
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
#library(ggpubr)
library(markdown)
library(shiny)
library(shinythemes)
library(tidyverse)
library(magrittr)
library(lubridate)
#library(plotly)
library(kableExtra)
library(knitr)
library("readxl")
library(writexl)
#library(RPostgreSQL)
#library(devtools)
library(remotes)
library(DBI)
library(tidyverse)
library(kableExtra)
#library(reldist)
library("readxl")
library("writexl")
library(kableExtra)
library(PerformanceAnalytics)
library("rio")
```

# 1 Formulación del modelo RLS

El modelo de Regresiśon lineal Simple de y sobre x se formula según:

$$
y = \beta_0 + \beta_1 \cdot x + \epsilon
$$





de forma que, para un valor dado de x = x, ˛ representa una desviaciśon aleatoria
de la respuesta y sobre el valor esperado segśun la recta de regresiśon:
E(yjx = x) = Ż0 + Ż1x: (5.2)
Los coeŻcientes de la regresiśon, esto es, los parśametros que estimaremos para
ajustar el modelo RLS son:
Ż0.- la interceptaciśon de la recta, esto es, la altura de la recta cuando x = 0.
Ż1.- la pendiente de la recta, que re°eja cuśanto varśła la respuesta media E(y)
cuando pasamos de observar x = x a x = x + 1.
Dada una muestra de valores observados f(xi; yi)gn i=1, el modelo (5.1) implica
que todas las observaciones responden a:
yi = Ż0 + Ż1xi + ˛i; i = 1; : : : ; n;
donde ˛i son errores aleatorios e incorrelados, con media cero y varianza cons-
tante ž2, caracterśłsticas que identiŻcan las hipśotesis bśasicas del modelo RLS, que
formulamos con mśas detalle a continuaciśon sobre los errores aleatorios ˛i:
Incorrelaciśon: Corr(˛i; ˛j) = 0. SigniŻca que las observaciones de la respuesta
y, y1; y2; : : : ; yn estśan incorreladas entre sśł, esto es, los valores de unas no
afectan a los de otras.
Media cero: E(˛i) = 0. Lo que implica que la respuesta esperada segśun el mo-
delo RLS depende linealmente de los coeŻcientes de regresiśon Ż0 y Ż1, al
tener como expresiśon (5.2).
Varianza constante: V ar(˛i) = ž2. Lo que signiŻca que las observaciones
fyi; i = 1; : : : ; ng provienen de una misma poblaciśon cuya variabilidad res-
pecto de sus medias fŻ0 + Ż1xi; i = 1; : : : ; ng viene dada por ž2







