---
title: Correlaciones entre variables del Censo de Viviendas, Hogares y Personas e ingresos promedios comunales de la CASEN 2017.
author:
- name: VE-CC-AJ
  affiliation: DataIntelligence
subtitle: | 

date: "Jueves 01-06-2021"

abstract: |
  Calculamos correlaciones entre el ingreso promedio comunal **multiplicado por la población comunal** que llamaremos **ingresos expandidos** extraído de la Casen 2017 y las frecuencias de categorías de respuesta para todas las variables del Censo de viviendas, hogares y personas al 2017, también extraídas a nivel comunal.
  
  Haremos las correlaciones tanto a nivel Urbano como rural.
  
  Importante es aplicar la libreria **dplyr** para evitar que en los filtros se desplieguen series de tiempo.
    
header-includes:
   - \usepackage[]{babel}

output:
  html_document:
    toc: true
    toc_float: true
    theme: flatly
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
#library(ggpubr)
library(markdown)
library(shiny)
library(shinythemes)
library(tidyverse)
library(magrittr)
library(lubridate)
#library(plotly)
library(kableExtra)
library(knitr)
library("readxl")
library(writexl)
#library(RPostgreSQL)
#library(devtools)
library(remotes)
library(DBI)
library(tidyverse)
library(kableExtra)
#library(reldist)
library("readxl")
library("writexl")
library(kableExtra)
library(PerformanceAnalytics)
library("rio")
library("dplyr")

```

# 1 Construcción de tablas con frecuencias de respuesta por categoría desde el Censo: **Personas** Urbano

Area:
urbano = 1 rural = 2
<br>

## 1.1 Pregunta **P08**: Sexo

1 Hombre\
2 Mujer

```{r, warning = FALSE}
tabla_con_clave <- readRDS("../censo_personas_con_clave_17")
tabla_con_clave <- filter(tabla_con_clave, tabla_con_clave$AREA == 1)
```

```{r, warning = FALSE}
b <- tabla_con_clave$COMUNA
c <- tabla_con_clave$P08
cross_tab =  xtabs( ~ unlist(b) + unlist(c))
tabla <- as.data.frame(cross_tab)
d <-tabla[!(tabla$Freq == 0),]
d$anio <- "2017"

d_t <- filter(d,d$unlist.c. == 1)
d_i <- filter(d,d$unlist.c. == 2)
d_t = merge( x = d_t, y = d_i, by = "unlist.b.", all.x = TRUE)

# Agregamos un cero a los códigos comunales de 4 dígitos, que queda en la columna llamada código:
codigos <- d_t$unlist.b.
rango <- seq(1:nrow(d_t))
cadena <- paste("0",codigos[rango], sep = "")
cadena <- substr(cadena,(nchar(cadena)[rango])-(4),6)
codigos <- as.data.frame(codigos)
cadena <- as.data.frame(cadena)
comuna_corr <- cbind(d_t,cadena)
comuna_corr <- comuna_corr[,-c(1),drop=FALSE]

names(comuna_corr)[7] <- "código" 

# Hacemos la unión con los ingresos promedio comunales expandidos:
ingresos_expandidos_2017 <- readRDS("Ingresos_expandidos_urbano_17.rds")
df_2017_2 = merge( x = comuna_corr, y = ingresos_expandidos_2017, by = "código", all.x = TRUE)

names(df_2017_2)[3] <- "hombre"
names(df_2017_2)[6] <- "mujer"

my_data <- df_2017_2[, c(3,6,13)]
chart.Correlation(my_data, histogram=TRUE, pch=20)
```


# 2 Construcción de tablas con frecuencias de respuesta por categoría desde el Censo: **Personas** Rural

Area:
urbano = 1 rural = 2
<br>

## 1.1 Pregunta **P08**: Sexo

1 Hombre\
2 Mujer

```{r, warning = FALSE}
tabla_con_clave <- readRDS("../censo_personas_con_clave_17")
tabla_con_clave <- filter(tabla_con_clave, tabla_con_clave$AREA == 2)
```

```{r, warning = FALSE}
b <- tabla_con_clave$COMUNA
c <- tabla_con_clave$P08
cross_tab =  xtabs( ~ unlist(b) + unlist(c))
tabla <- as.data.frame(cross_tab)
d <-tabla[!(tabla$Freq == 0),]
d$anio <- "2017"

d_t <- filter(d,d$unlist.c. == 1)
d_i <- filter(d,d$unlist.c. == 2)
d_t = merge( x = d_t, y = d_i, by = "unlist.b.", all.x = TRUE)

# Agregamos un cero a los códigos comunales de 4 dígitos, que queda en la columna llamada código:
codigos <- d_t$unlist.b.
rango <- seq(1:nrow(d_t))
cadena <- paste("0",codigos[rango], sep = "")
cadena <- substr(cadena,(nchar(cadena)[rango])-(4),6)
codigos <- as.data.frame(codigos)
cadena <- as.data.frame(cadena)
comuna_corr <- cbind(d_t,cadena)
comuna_corr <- comuna_corr[,-c(1),drop=FALSE]

names(comuna_corr)[7] <- "código" 

# Hacemos la unión con los ingresos promedio comunales expandidos:
ingresos_expandidos_2017 <- readRDS("Ingresos_expandidos_rural_17.rds")
df_2017_2 = merge( x = comuna_corr, y = ingresos_expandidos_2017, by = "código", all.x = TRUE)

names(df_2017_2)[3] <- "hombre"
names(df_2017_2)[6] <- "mujer"

my_data <- df_2017_2[, c(3,6,13)]
chart.Correlation(my_data, histogram=TRUE, pch=20)
```















<hr style="height:5px;border-width:5;color:Green;background-color:Green">
<br>

