---
title: Expansión de la CASEN sobre el CENSO compendio 2017
author:
- name: VE-CC-AJ
  affiliation: DataIntelligence
subtitle: | 
  Correlaciones

date: "Viernes 02-07-2021"

abstract: |
  Exponemos las correlaciones descubiertas.
  
header-includes:
   - \usepackage[]{babel}

output:
  html_document:
    toc: true
    toc_float: true
    theme: flatly
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
#library(ggpubr)
library(markdown)
library(shiny)
library(shinythemes)
library(tidyverse)
library(magrittr)
library(lubridate)
#library(plotly)
library(kableExtra)
library(knitr)
library("readxl")
library(writexl)
#library(RPostgreSQL)
#library(devtools)
library(remotes)
library(DBI)
library(tidyverse)
library(kableExtra)
#library(reldist)
library("readxl")
library("writexl")
library(kableExtra)
library(PerformanceAnalytics)
library("rio")
library(ggplot2)
```

# 1 Censo Vivienda 2017

<hr style="height:3px;border-width:3;color:Green;background-color:Green">

## 1.1 **P01**: Tipo de vivienda

[Correlaciones **P01**](https://rpubs.com/dataintelligence/corr_cc_P01)

## 1.2 *Variable que más correlaciona con ingresos expandidos*: 

Urbano: "Casa" (**0,95**) 

Rural: "Móvil (carpa, casa rodante o similar)" (**0,35**)

<hr style="height:1px;border-width:3;color:Green;background-color:Green">

## 1.3 **P02**: Ocupación de la vivienda

1 Con moradores presentes\
2 Con moradores ausentes\
3 En venta, para arriendo, abandonada u otro\
4 De temporada (vacacional u otro)

<span style="color:red">¿Resulta relevante?</span>

<hr style="height:1px;border-width:3;color:Green;background-color:Green">

## 1.4 **P03A**: Material de los muros exteriores

[Correlaciones **P03A**](https://rpubs.com/dataintelligence/corr_censo_casen_P03A)

## 1.5 Variable que más correlaciona a nivel: 

Urbano: "Albañilería: bloque de cemento, piedra o ladrillo" (**0,92**) 

Rural: "Hormigón" (**0,37**)

<hr style="height:1px;border-width:3;color:Green;background-color:Green">

## 1.6 **P03B**: Material en la cubierta del techo

[Correlaciones **P03B**](https://rpubs.com/dataintelligence/corr_cc_P03B)

## 1.7 Variable que más correlaciona a nivel: 

Urbano: "Tejas o tejuelas de arcilla, metálicas, de cemento, de madera, asfálticas o plásticas" (**0,94**) 

Rural: "Tejas o tejuelas de arcilla, metálicas, de cemento, de madera, asfálticas o plásticas" (**0,41**)

<hr style="height:1px;border-width:3;color:Green;background-color:Green">

## 1.8 **P03C**: Material de construcción del piso

[Correlaciones **P03C**](https://rpubs.com/dataintelligence/corr_cc_P03C)

## 1.9 Variable que más correlaciona a nivel: 

Urbano: "Parquet, piso flotante, cerámico, madera, alfombra, flexit, cubrepiso u otro similar, sobre radier o vigas de madera" (**0,98**) 

Rural: "Parquet, piso flotante, cerámico, madera, alfombra, flexit, cubrepiso u otro similar, sobre radier o vigas de madera" (**0,34**)

<hr style="height:1px;border-width:3;color:Green;background-color:Green">

## 1.10 **P04**: Número de piezas usadas exclusivamente como dormitorio

[Correlaciones **P04**](https://rpubs.com/dataintelligence/corr_cc_P04)

## 1.11 Variable que más correlaciona a nivel: 

Urbano: "2 y 3 piezas" (**0,98**) 

Rural: "4 piezas" (**0,4**)

<hr style="height:1px;border-width:3;color:Green;background-color:Green">

## 1.12 **P05**: Origen del agua

[Correlaciones **P05**](https://rpubs.com/dataintelligence/corr_cc_P05)

## 1.13 Variable que más correlaciona a nivel: 

Urbano: "Red pública" (**0,99**) 

Rural: "Camión aljibe" (**0,34**)

<hr style="height:1px;border-width:3;color:Green;background-color:Green">

## 1.14 **CANT_HOG**: Cantidad de hogares

[Correlaciones **CANT_HOG**](https://rpubs.com/dataintelligence/corr_cc_CANT_HOG)

## 1.15 Variable que más correlaciona a nivel: 

Urbano: "1 hogar" (**0,99**) 

Rural: "6 hogares" (**0,49**)

<hr style="height:1px;border-width:3;color:Green;background-color:Green">

## 1.16 **CANT_PER**: Cantidad de personas

[Correlaciones **CANT_PER**](https://rpubs.com/dataintelligence/corr_censo_casen_CANT_PER)

## 1.17 Variable que más correlaciona a nivel: 

Urbano: "4 personas" (**0,98**) 

Rural: "8 y 9 personas" (**0,38**)

<hr style="height:3px;border-width:3;color:Green;background-color:Green">

# 2 Censo Hogar 2017

<hr style="height:3px;border-width:3;color:Green;background-color:Green">

### 2.1 TIPO_HOGAR <span style="color:red">(pendiente)</span>

1 Hogar unipersonal\
2 Hogar nuclear monoparental\
3 Hogar nuclear biparental sin hijos\
4 Hogar nuclear biparental con hijos\
5 Hogar compuesto\
6 Hogar extenso\
7 Hogar sin núcleo\
98 No aplica\
99 Missing\

### 2.2 TIPO_OPERATIVO <span style="color:red">(pendiente)</span>

1 Hogar en vivienda particular\
8 Vivienda colectiva (no es hogar)\
9 Operativo personas en tránsito (no es hogar)\
10 Operativo calle (no es hogar)\

<hr style="height:3px;border-width:3;color:Green;background-color:Green">

# 3 Censo Personas 2017

<hr style="height:3px;border-width:3;color:Green;background-color:Green">

## 3.1 **P07**: Relación de parentesco

1 Jefe/a de hogar\
2 Esposo/a o cónyuge\
3 Conviviente por unión civil\
4 Conviviente de hecho o pareja\
5 Hijo/a\
6 Hijo/a del cónyuge, conviviente o pareja\
7 Hermano/a\
8 Padre/madre\
9 Cuñado/a\
10 Suegro/a\
11 Yerno/nuera\
12 Nieto/a\
13 Abuelo/a\
14 Otro pariente\
15 No pariente\
16 Servicio doméstico puertas adentro\
17 Persona en vivienda colectiva\
18 Persona en tránsito\
19 Persona en operativo calle\

P07 <span style="color:red">¿Resulta relevante?</span>

<hr style="height:1px;border-width:3;color:Green;background-color:Green">

## 3.2 **P08**: Sexo

[Correlaciones **P08**](https://rpubs.com/dataintelligence/corr_censo_casen_P08)

## 3.3 Variable que más correlaciona a nivel: 

Urbano: "hombre, mujer" (**0,98**) 

Rural: "hombre" (**0,35**)

<hr style="height:1px;border-width:3;color:Green;background-color:Green">

## 3.4 **P09**: Edad

[Correlaciones **P09**](https://rpubs.com/dataintelligence/corr_censo_casen_P09)

## 3.5 Variable que más correlaciona a nivel: 

Urbano: "35,36,37,38,39,40,41,42" (**0,99**) 

Rural: "18" (**0,44**)

<hr style="height:2px;border-width:3;color:Red;background-color:Red">

### Relevancias

P10: Residencia habitual

1 En esta vivienda
2 En otra vivienda
3 En otra comuna
4 En otro país
98 No Aplica 
99 Missing

P10 <span style="color:red">¿Resulta relevante?</span>

P10COMUNA 
P11COMUNA 
P12COMUNA

Comuna de residencia habitual Comuna de residencia hace 5 años Comuna de nacimiento

P10COMUNA, P11COMUNA, P12COMUNA <span style="color:red">¿Resulta relevante?</span>

P10PAIS País de residencia habitual
P11PAIS País de residencia hace 5 años
P12PAIS País de nacimiento

P10PAIS, P11PAIS, P12PAIS <span style="color:red">¿Resulta relevante?</span>

P11 Residencia hace 5 años
P12 Lugar de nacimiento
P12A_LLEGADA Año de llegada al país
P12A_TRAMO Período de llegada al País

P11, P12 , P12A_LLEGADA, P12A_TRAMO  <span style="color:red">¿Resultan relevantes?</span>

<hr style="height:2px;border-width:3;color:Red;background-color:Red">

## 3.6 **P15**: Nivel del curso más alto aprobado

[Correlaciones **P15**](https://rpubs.com/dataintelligence/corr_censo_casen_P15)

## 3.7 Variable que más correlaciona a nivel: 

Urbano: "Técnico superior" (**0,98**) 

Rural: "Técnica comercial" (**0,46**)

<hr style="height:1px;border-width:3;color:Green;background-color:Green">

<hr style="height:2px;border-width:3;color:Red;background-color:Red">
Se debe hacer un análisis más profundo que correlacione conjuntamente Nivel del curso más alto aprobado (P15) y Curso o años más alto aprobado (p14) y Completó el nivel especificado (P15A)
<hr style="height:2px;border-width:3;color:Red;background-color:Red">

## 3.8 **P13**: Asiste actualmente a la educación formal <span style="color:red">(pendiente)</span>


<hr style="height:1px;border-width:3;color:Green;background-color:Green">

## 3.9 **P16**: Se considera perteneciente a un pueblo indígena u originario <span style="color:red">(pendiente)</span>


<hr style="height:1px;border-width:3;color:Green;background-color:Green">


## 3.9 **P16A**: Pueblo indígena u originario listado

[Correlaciones **P16A**](https://rpubs.com/dataintelligence/corr_censo_casen_P16A_GRUPO)

## 3.10 Variable que más correlaciona a nivel: 

Urbano: "Rapa Nui" (**0,88**) 

Rural: "Quechua" (**0,23**)

<hr style="height:1px;border-width:3;color:Green;background-color:Green">

P16A_OTRO: Pueblo indígena u originario (Otro)  <span style="color:red">(pendiente)</span>


## 3.11 **P17**: Trabajó durante la semana pasada

[Correlaciones **P17**](https://rpubs.com/dataintelligence/corr_censo_casen_P17)

## 3.12 Variable que más correlaciona a nivel: 

Urbano: "Por un pago" y "Tenía empleo pero estuvo de vacaciones, con licencia, en descanso laboral, etc." (**0,99**) 

Rural: "Otra situación" (**0,47**)

<hr style="height:1px;border-width:3;color:Green;background-color:Green">


## 3.13 **P18**: Trabajó durante la semana pasada

[Correlaciones **P18**](https://rpubs.com/dataintelligence/corr_censo_casen_P18)

## 3.14 Variable que más correlaciona a nivel: 

Urbano: "Rama no declarada" (**0,98**) 

Rural: "Otras actividades de servicios" (**0,47**)

<hr style="height:1px;border-width:3;color:Green;background-color:Green">


## 3.15 **P19**: Total hijos/as nacidos vivos

[Correlaciones **P19**](https://rpubs.com/dataintelligence/corr_cc_P19)

## 3.16 Variable que más correlaciona a nivel: 

Urbano: "1 hijo (Pearson)" (**0,99**) 

Rural: "0 hijos" (**0,34**)

<hr style="height:1px;border-width:3;color:Green;background-color:Green">


## 3.17 **P20**: Total hijos/as nacidos vivos

[Correlaciones **P20**](https://rpubs.com/dataintelligence/corr_cc_P20)

## 3.18 Variable que más correlaciona a nivel: 

Urbano: "1 hijo (Pearson)" (**0,99**) 

Rural: "2 y 3 hijos" (**0,36**)

<hr style="height:1px;border-width:3;color:Green;background-color:Green">


<hr style="height:1px;border-width:3;color:Red;background-color:Red">

P21M Mes de nacimiento del último/a hijo/a

P21A Año de nacimiento del último/a hijo/a

P10PAIS_GRUPO País de residencia habitual (grupo)

P11PAIS_GRUPO País de residencia hace 5 años (grupo)

P12PAIS_GRUPO País de nacimiento (grupo)

P21M, P21A, P10PAIS_GRUPO, P11PAIS_GRUPO, P12PAIS_GRUPO 

<span style="color:red">¿Resulta relevante?</span>

<hr style="height:1px;border-width:3;color:Red;background-color:Red">






## 3.17 **ESCOLARIDAD**: Años de escolaridad

[Correlaciones **ESCOLARIDAD**](https://rpubs.com/dataintelligence/corr_cc_esc)

## 3.18 Variable que más correlaciona a nivel: 

Urbano: "14 años" (**0,99**) 

Rural: "13 años" (**0,43**)

<hr style="height:1px;border-width:3;color:Green;background-color:Green">





## 3.17 **P16A_GRUPO**: Pueblo indígena u originario (grupo) <span style="color:red">(pendiente)</span>

<hr style="height:1px;border-width:3;color:Green;background-color:Green">


https://github.com/rasbt/pattern_classification/blob/master/resources/latex_equations.md#correlation---pearson



